version: "3"
services:

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service
    restart: always

  order-service:
    build:
      context: .
      dockerfile: order/Dockerfile
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - order-db
      - stock-db
      - payment-db
    restart: always

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb --appendonly yes
    ports:
      - "6380:6379"
    restart: always

  stock-service:
    build:
      context: .
      dockerfile: stock/Dockerfile
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    environment:
      - ORDER_REDIS_HOST=order-db
      - ORDER_REDIS_PORT=6379
      - ORDER_REDIS_PASSWORD=redis
      - ORDER_REDIS_DB=0
    depends_on:
      - stock-db
      - order-db
    restart: always

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb --appendonly yes
    ports:
      - "6381:6379"
    restart: always

  payment-service:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    environment:
      - ORDER_REDIS_HOST=order-db
      - ORDER_REDIS_PORT=6379
      - ORDER_REDIS_PASSWORD=redis
      - ORDER_REDIS_DB=0
    depends_on:
      - payment-db
      - order-db
    restart: always

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb --appendonly yes
    restart: always